CREATE DATABASE bid_item_db;
USE bid_item_db;

CREATE TABLE Departments
( 
DeptCode VARCHAR(4) NOT NULL,
DeptName VARCHAR(25) NOT NULL,

CONSTRAINT PK_CODE PRIMARY KEY(DeptCode)
);

CREATE TABLE Items
(
ItemID INT AUTO_INCREMENT,
ItemName VARCHAR(25) NOT NULL,
ItemDescr VARCHAR(100),
CurrBid FLOAT(5,2) DEFAULT 1 NOT NULL,
DeptCode VARCHAR(4) NOT NULL,

CONSTRAINT PK_ITEMID PRIMARY KEY(ItemID),
CONSTRAINT FK_DEPTCODE FOREIGN KEY(DeptCode) REFERENCES Departments(DeptCode)
);

CREATE TABLE Bids
(
BidID INT AUTO_INCREMENT,
BidderF_Name VARCHAR(15) NOT NULL,
BidderL_Name VARCHAR(25) NOT NULL,
BidderEmail VARCHAR(25) NOT NULL,
BidAmount FLOAT(5,2) NOT NULL,
ItemID INT NOT NULL,

CONSTRAINT PK_BIDID PRIMARY KEY(BidID),
CONSTRAINT FK_ITEMID FOREIGN KEY(ItemID) REFERENCES Items(ItemID)
);